# Generated by Django 3.0.1 on 2020-05-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0006_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandant',
            name='Currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meas.Currency'),
        ),
    ]
