# Generated by Django 3.0.1 on 2020-05-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0007_mandant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_pppu_net',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Einkaufspreis pro Einheit (netto)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_sppu_net',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Verkaufspreis pro Einheit (netto)'),
        ),
    ]
