# Generated by Django 3.0.1 on 2020-05-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0009_auto_20200521_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Currency_symbol',
            field=models.SlugField(max_length=10, verbose_name='Währungssymbol'),
        ),
    ]
