# Generated by Django 3.0.1 on 2020-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0010_auto_20200521_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Currency_symbol',
            field=models.CharField(max_length=30, verbose_name='Währungssymbol'),
        ),
    ]
