# Generated by Django 3.0.1 on 2020-05-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0011_auto_20200521_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['Currency_id']},
        ),
    ]
