# Generated by Django 3.0.1 on 2020-06-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0013_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_time_act',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Order_time_sch',
        ),
        migrations.AddField(
            model_name='order',
            name='Order_status',
            field=models.SmallIntegerField(choices=[(0, 'created'), (1, 'not yet scheduled'), (2, 'scheduled'), (3, 'in progress'), (4, 'fullfilld'), (5, 'completed'), (6, 'cancelled')], default=0, verbose_name='Auftragsstatus'),
        ),
        migrations.CreateModel(
            name='Related_Service',
            fields=[
                ('Related_Service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Related_Service_ia', models.DateTimeField(auto_now=True, verbose_name='Hinzugefügt am')),
                ('Related_Service_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas.Product')),
                ('Service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_start', models.DateTimeField(verbose_name='Start')),
                ('Appointment_end', models.DateTimeField(verbose_name='Ende')),
                ('Appointment_note', models.CharField(blank=True, max_length=254, null=True)),
                ('Appointment_ia', models.DateTimeField(auto_now=True, verbose_name='Hinzugefügt am')),
                ('Appointment_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('Employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas.Employee')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas.Order')),
            ],
        ),
    ]
